### ISSUE TITLE
Example is not working

### ISSUE THREAD

**Issue by mahnerak** [WillBrennan/MNIST#1]
```
>>> ConvNet = DeepConv.DeepConv()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
TypeError: __init__() takes exactly 2 arguments (1 given)
```

**Comment by WillBrennan** [comment]
Fixed issue, updated readme, also adjusted the arguments for the DeepConv class, a little bit more readable now.

Suggest just running `main.py` instead of using the example.
